### ISSUE TITLE
SPI with name Lucene50 does not exist

### ISSUE THREAD

**Issue by srdealx** [ozlerhakan/mongolastic#12]
Won't run : 

> `An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names [es090, completion090, XBloomFilter]`

config type: **misc.direction: em**

**Comment by ozlerhakan** [comment]
Do you have it after trying the latest one of mongolastic? Which elasticsearch version do you have?

**Comment by srdealx** [comment]
Have ElasticSearch 2.3.1 and used the latest version available at the time
of the issue

**Comment by srdealx** [comment]
Sorry it was elastic 2.3.3

**Comment by ozlerhakan** [comment]
Could you please try this [option](https://github.com/dadoonet/elasticsearch/blob/a4e22b44e49ac01d9011d50442c5c929597204a2/docs/java-api/index.asciidoc#embedding-jar-with-dependencies).

Just add these lines  into `maven-shade-plugin` plugin of the pom.xml and run `mvn clean install -DskipTests`, and rerun your config file with the newly created `mongolastic.jar`.

```
 <configuration>
  <transformers>
     <transformer implementation="org.apache.maven.plugins.shade.resource.PluginXmlResourceTransformer"/>
     <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
       <mainClass>com.kodcu.main.Mongolastic</mainClass>
    </transformer>
  </transformers>
 </configuration>
```

**Comment by ozlerhakan** [comment]
did you try @srdealx ?

**Comment by srdealx** [comment]
Sry Hakan didn't get the tim to do it yet.

**Comment by ozlerhakan** [comment]
1.3.7 should fix this issue @srdealx

**Comment by jmmk** [comment]
@ozlerhakan 
You may need to add `<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>`

The Lucene codecs are in META-INF/services, and if you look at the Maven Shade docs:

> JAR files providing implementations of some interfaces often ship with a META-INF/services/ directory that maps interfaces to their implementation classes for lookup by the service locator. To relocate the class names of these implementation classes, and to To merge multiple implementations of the same interface into one service entry, the ServicesResourceTransformer can be used

This allows it to combine the codecs from conflicting JARs instead of clobbering them.

Note: I did not run into this issue with Mongolastic, but I did on another project using ES. Possibly a difference in ES 2.3.1 and 2.3.3 JARs?

**Comment by ozlerhakan** [comment]
Hi @jmmk ,

Thank you for informing me about it. I can probably add this option for the next release but I don't remember whether I encountered such an error before ES 2.3.1, there are possibly slightly differences between two versions.
