### ISSUE TITLE
ES to mongo transfer issue

### ISSUE THREAD

**Issue by c-yoon** [ozlerhakan/mongolastic#22]
Hi, it looks like ElasticToMongoProvider (in buildJSONContent) is not shifting the scroll window. 
It might be pulling and transferring the same data over and over again to the target mongo database.

**Comment by ozlerhakan** [comment]
Hi @c-yoon ,

Thank you for your support, I will look into this issue.

**Comment by ozlerhakan** [comment]
could you try 1.4.2 out @c-yoon ?

**Comment by ozlerhakan** [comment]
I am closing the issue, If v1.4.2  is not solving the problem pls ping me.
