### ISSUE TITLE
Date is stored as string in mongodb

### ISSUE THREAD

**Issue by mindcrusher11** [ozlerhakan/mongolastic#29]
I am transferring data from elasticsearch to mongodb but date column is stored as string.

**Comment by winder** [comment]
You can configure the format with the `dateFormat` option, or look at `CustomDateFormat.java` for how that serialization is done.

It looks like the code should use the default `DateFormat` implementation if you set that value to null.

**Comment by mindcrusher11** [comment]
I have configured deatformat as well.

"dateFormat": "MM-dd-yy",
"longToString": true

Thanks
Gaurhari
