### ISSUE TITLE
could have a option to update / replace the same _id row?

### ISSUE THREAD

**Issue by agrozyme** [ozlerhakan/mongolastic#30]
I wish to trasnfer data from mongodb to ES, and I don't want to set 'query' or 'project'.
could have a option to update / replace the same _id row?

**Comment by ozlerhakan** [comment]
Hi @agrozyme , 

The tool doesn't provide an update/replace option. It only transfers the data itself between two platforms.

**Comment by agrozyme** [comment]
OK, thanks
